### ISSUE TITLE
Important TODO'S

### ISSUE THREAD

**Issue by SamCZ** [SamCZ/Aurora#5]
- [x] Add shader permutations
- [x] Fix input layout buffer bindings
- [ ] Add blend states
- [ ] Add texture compression https://github.com/Ericsson/ETCPACK
